### ISSUE TITLE
IndieAuth login misses the path part of provided account URL

### ISSUE THREAD

**Issue by elf-pavlik** [kylewm/woodwind#22]
Similar to https://github.com/aaronpk/webmention.io/issues/47
I try to authenticate as _https://wwelves.org/perpetual-tripper_ and it greets me just as _wwelves.org_

**Comment by karadaisy** [comment]
fixed in b3cf4e7d0095ded30078f22832342eb6f584d436 so that it now uses the full URL we get from the authorization endpoint.

note that IndieAuth.com strips trailing /'s, which is unfortunate because it means that you have a different URL (and therefore a different account) coming from indiecert vs. indieauth
